replicaCount: 2

image:
  repository: fabops/telemetry-ingestion
  tag: "0.0.1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

kafka:
  bootstrapServers: kafka.fabops.svc.cluster.local:9092

schemaRegistry:
  url: http://schema-registry.fabops.svc.cluster.local:8081

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
